config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: 'json' } do

    namespace :v2 do
      jsonapi_resources :sites, only: [:index, :show, :update]
    end

    namespace :v1 do
      namespace :customer_portal do
        resource :customer, only: [:show]
      end

      post 'opportunities' => 'opportunities#create'

      get 'adjustor_portal', to: 'adjustor_portal/adjustors#show'

      resources :home, only: :index
      resources :users, only: :index do
        get 'me' => 'users#show', on: :collection
      end
      put :sign_in, to: 'sessions#create'
      put :users, to: 'registrations#update'
      delete :sign_out, to: 'sessions#destroy'
      post 'users/password', to: 'passwords#create'
      put 'users/password', to: 'passwords#update'
      resources :sites, only: [:index, :create, :update, :show, :destroy] do
        resources :assets, only: [:index, :create, :update, :show, :destroy]
        resources :documents, only: [:index, :create, :update, :show]
        resources :insurance_adjustors, only: [:show, :create, :update]
        resources :images, only: [:index, :create, :update, :show]
        resource :project, only: [:show, :create, :update]
        resources :billings, only: [:create, :update, :show]
        resources :productions, only: [:create, :update, :show]
        resource :contract, only: [:show, :create, :update] do
          post :send_to_customer
          post :send_to_insurance_adjustor
        end
      end
      resources :customers, only: [:index, :create, :update, :show, :destroy]
      resources :appointments, only: [:index, :create, :update, :show, :destroy]
      resource :customer_session, only: [:new, :create, :destroy]
    end
  end

  resources :sites, only: [] do
    resources :assets, only: [:create, :update, :index, :destroy]
  end

  resources :attachments

  [:admin, :office_staff, :sales_rep].each do |role|
    namespace role do
      resources :sites do
        get :autocomplete_site_customer, on: :collection
      end
    end
  end

  devise_for :users, controllers: { sessions: 'sessions', registrations: "registrations" ,
                                    :omniauth_callbacks => "omniauth_callbacks" }

  match "users/auth/google_oauth2/callback" => "omniauth_callbacks#google_oauth2", via: [:get, :post]

  devise_scope :user do
    get 'users/sign_out', to: 'sessions#destroy'

    authenticated :user do
      ActiveAdmin.routes(self) if !ARGV.grep(/assets:precompile/).any? && !ARGV.grep(/db:migrate/).any? && !ARGV.grep(/db:seed/).any?
    end

    root to: 'sessions#new'
  end

  get '*unmatched_route', to: redirect('/')
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  audited

  belongs_to :viewable, polymorphic: true, touch: true
  has_many :attachments, dependent: :destroy, inverse_of: :asset
  accepts_nested_attributes_for :attachments, allow_destroy: true

  SUBCLASS = ['Document', 'Image']
  DOC_TYPE = { 1 => 'Billing Reference Document', 2 => 'Completion Payment Check', 3 => 'Customer Invoice',
              4 => 'Deductible Check', 5 => 'EagleView', 6 => 'HOA Approval Document', 7 => 'Initial Payment Check',
              8 => 'Insurance scope document', 9 => 'Material List', 10 => 'Supplement Documentation',
              11 => 'Trade work Bid', 12 => 'Xactimate', 13 => 'Other', 14 => 'Supplier Invoice',
              15 => 'Material Invoice'}

  validates :type, :viewable, :attachments, presence: true

  scope :images, -> { where(type: 'Image') }
  scope :docs, -> { where(type: 'Document') }

  before_validation :set_stage, unless: :stage?
  before_validation :set_title, unless: :title?

  def document?
    is_a?(Document)
  end

  def image?
    is_a?(Image)
  end



  private
    def set_title
      if doc_type != DOC_TYPE.key('Other')
        self.title = DOC_TYPE[doc_type]
      end
    end

    def set_stage
      if viewable.is_a?(Site)
        self.stage = Site::STAGE[viewable.stage.try(:to_sym) || :lead]
      end
    end


end

app/controllers/api/v1/assets_controller.rb
class Api::V1::AssetsController < Api::V1::BaseController
  before_action :find_site
  before_action :find_asset, only: [:update, :show, :destroy]

  def index
    @search = @site.assets.ransack(search_params)
    @assets = @search.result(distinct: true).includes(:attachments)
    respond_with(@assets)
  end

  def create
    @asset = @site.assets.build(asset_params(:create))
    @asset.save
    respond_with(@asset)
  end

  def update
    @asset.update_attributes(asset_params(:update))
    respond_with(@asset)
  end

  def show
    respond_with(@asset)
  end

  def destroy
    if @asset.destroy
      render json: {success: true, status: 200}
    else
      render json: {success: false, status: 402}
    end
  end

  private
    def asset_params(action=:create)
      parse_encoded_attachments
      if action == :create
        params.permit(:type, :notes, :doc_type, :title, :position, :description, :stage, :alt, attachments_attributes: [:file, :_destroy])
      elsif action == :update
        params.permit(:id, :type, :notes, :doc_type, :title, :position, :description, :stage, :alt, attachments_attributes: [:file, :_destroy, :id])
      end
    end

    def search_params
      params[:q] ||= {}
      params[:q][:s] ||= 'updated_at desc'
      params[:q]
    end

    def parse_encoded_attachments
      if params[:attachments_attributes]
        params[:attachments_attributes].each do |k, v|
          if v[:encoded_attachment_data]
            encoded_attachment_data = v.delete(:encoded_attachment_data)
            attachment_format = v.delete(:attachment_format)
            v[:file] = attachment_obj(encoded_attachment_data, attachment_format)
          end
        end
      end
    end

    def find_asset
      unless @asset = @site.assets.includes(:attachments).find_by(id: params[:id])
        render_with_failure(msg: 'Asset Not Found', status: 404)
      end
    end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_site
  before_action :find_asset, only: [:update, :destroy]
  before_action :set_file_type, only: [:create]

  def index
    @asset = Asset.new
    respond_to do |format|
      format.html { render 'index'}
      format.json {
        @assets = get_assets
        render :json => @assets.map { |asset| asset.attachments.first.to_jq_upload }.to_json 
      }
    end
    
  end

  def update
    respond_to do |format|
      if(@asset.update_attributes(asset_params))
        format.json { render json: {:text => "ok"}, :status => 200  }
      else
        format.json { render json: {:error => "custom_failure"}, :status => 422  }
      end
      format.html { render 'index', error: 'Item could not be deleted' }
    end
  end

  def destroy
    respond_to do |format|
      if @asset.destroy()
        format.json { render json: {:text => "ok"}, :status => 200  }
      else
        format.json { render json: {:error => "custom_failure"}, :status => 422  }
      end
      format.html { render 'index', error: 'Item could not be deleted', :status => 422 }
    end
  end

  def create
    @asset = @site.assets.build(asset_params)
    respond_to do |format|
      if @asset.save
        format.html {
          render :json => [@asset.attachments.first.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json { render json: {files: [@asset.attachments.first.to_jq_upload]}, status: :created }
      else
        format.html { render action: "index" }
        format.json { render :json => [{:error => "custom_failure"}], :status => 422 }
      end
    end
  end

private

  def set_file_type
    if asset_params[:attachments_attributes][0][:file].content_type.match('image')
      asset_params[:type] = 'Image'
    else
      asset_params[:type] = 'Document'
    end
  end

  def asset_params
    params.require(:asset).permit!
  end

  def find_site
    unless @site = Site.accessible_by(current_ability, :read).find_by(id: params[:site_id])
      render_with_failure(msg: 'Site Not Found', status: 404)
    end
  end

  def find_asset
    @asset = @site.assets.where(id: params[:id]).first
    not_found unless @asset
  end

  def get_assets
    unless(params[:filter])
      @assets = @site.assets.includes(:attachments, :viewable)
    else
      params[:filter] == 'Image' ? @site.images.includes(:attachments, :viewable) : @site.documents.includes(:attachments, :viewable)
    end
  end

  
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/index.html.erb
<% content_for(:body_attributes) do %>
  data-no-turbolink="true"
<% end %>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<header class="navbar navbar-static-top navbar-default" id="top" role="banner">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="../" class="navbar-brand"><%= COMPANY_NAME %></a>
    </div>
    <nav id="bs-navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="/admin/dashboard">Dashboard</a>
        </li>
        <li>
          <a href="/admin/customers">Customers</a>
        </li>
        <li class="active">
          <li id="sites"><a href="/admin/sites">Sites</a></li>
        </li>
        <li>
          <a href="/admin/appointments">Appointments</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/admin/users/<%= current_user.id %>"><%= current_user.email %></a></li>
        <li><a data-method="get" href="/users/sign_out">Logout</a></li>
      </ul>
    </nav>
  </div>
</header>


<div class="container-fluid">
  <div class="row">
    <div class="col-xs-120">
      <!-- The file upload form used as target for the file upload widget -->
      <%= form_for  @asset, url: site_assets_path, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
          <!-- Redirect browsers with JavaScript disabled to the origin page -->
          <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
          <div class="row fileupload-buttonbar">
              <div class="col-lg-7">
                  <!-- The fileinput-button span is used to style the file input field as button -->
                  <%= link_to @site.name, admin_site_url(@site), class: 'btn btn-primary' %>
                  <span class="btn btn-success fileinput-button">
                    <span>Add files...</span>
                    <%= file_field_tag 'asset[attachments_attributes][][file]', :multiple => true %>
                  </span>
                  <button type="submit" class="btn btn-primary start">
                    <span>Start upload</span>
                  </button>

                  <button id='update-all-link' class="btn btn-primary start">
                    <span>Update All</span>
                  </button>

                  <%= link_to 'All', site_assets_path(site_id: @site.id), class: 'btn btn-primary' %>

                  <%= link_to 'Images', site_assets_path(site_id: @site.id, filter: 'Image'), class: 'btn btn-primary' %>

                  <%= link_to 'Documents', site_assets_path(site_id: @site.id, filter: 'Document'), class: 'btn btn-primary' %>
                  <!-- <button type="reset" class="btn btn-warning cancel">
                      <i class="glyphicon glyphicon-ban-circle"></i>
                      <span>Cancel upload</span>
                  </button> -->
                  <!-- The global file processing state -->
                  <span class="fileupload-process"></span>
              </div>
              <!-- The global progress state -->
              <div class="col-lg-5 fileupload-progress fade">
                  <!-- The global progress bar -->
                  <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                      <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                  </div>
                  <!-- The extended global progress state -->
                  <div class="progress-extended">&nbsp;</div>
              </div>
          </div>
          <!-- The table listing the files available for upload/download -->
          <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
      <% end %>
    </div>
  </div>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td class="title"><label>Title: <input style='display:block' type='text' name="asset[title]"></label></td>
        <td>
          <label>Stage:</label>
          <select id="image_stage" style='display:block' name="asset[stage]"><option value=""></option>
            <option selected='selected' value="1">Lead</option>
            <option value="2">Contract</option>
            <option value="3">Project</option>
            <option value="4">Production</option>
            <option value="5">Billing</option>
          </select>
        </td>
        <td class="title"><label>Additional Notes: <textarea name='asset[notes]' rows='4'> </textarea></label></td>

        <td>

          {% if (!file.type.match('image')) { %}
            <select name="asset[doc_type]">
              <% Asset::DOC_TYPE.each_pair do |id, name| %>
                <%= content_tag :option, name, value: id -%>
              <% end %>
            </select>
          {% } %}
        </td>
        <td>
          <p class="size">Processing...</p>
          <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start btn-sm" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel btn-sm">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0; i < o.files.length; i++) { %}
    {% var file = o.files[i]; %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnail_url && file.content_type.match(/image/g)) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img style='width: 100px;' src="{%=file.thumbnail_url%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnail_url?'data-gallery':''%}>{%=(file.title ? file.title : file.name) %}</a> | <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnail_url?'data-gallery':''%}>Download</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td class="title"><label>Title: <input style='display:block' value='{%=file.title%}' type='text' name="asset[title]"></label></td>
        <td>
          <label>Stage:</label>
          <select id="image_stage" style='display:block' name="asset[stage]"><option value=""></option>
            <option {%= file.stage == 1 ? 'selected=1' : '' %} value="1">Lead</option>
            <option {%= file.stage == 2 ? 'selected=1' : '' %} value="2">Contract</option>
            <option {%= file.stage == 3 ? 'selected=1' : '' %} value="3">Project</option>
            <option {%= file.stage == 4 ? 'selected=1' : '' %} value="4">Production</option>
            <option {%= file.stage == 5 ? 'selected=1' : '' %} value="5">Billing</option>
          </select>
        </td>
        <td class="title"><label>Additional Notes: <textarea value='{%=file.notes%}' name='asset[notes]' rows='4'> {%=file.notes%}</textarea></label>
        </td>

        <td>

          {% if (!file.type.match('image')) { %}
            <select name="asset[doc_type]">
              <% Asset::DOC_TYPE.each_pair do |id, name| %>
                <option {%= file.doc_type == <%= id %> ? 'selected=1' : '' %} value="<%= id %>"><%= name %></option>
              <% end %>
            </select>
          {% } %}
        </td>

        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>

        <td>
          {% if (file.update_url) { %}
            <button class='btn btn-primary btn-sm update-link' data-method="PUT" data-remote='true' data-url="{%=file.update_url%}" >
              <i class="glyphicon glyphicon-pencil"></i>
              <span>Update</span>
            </button>
          {% } %}

          {% if (file.delete_url) { %}
              <a onclick="return confirm('Are you sure?')" class='btn btn-sm btn-warning delete-link' data-method="DELETE" data-remote='true' href="{%=file.delete_url%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
              </a>
          {% } else { %}
              <button class="btn btn-sm btn-warning cancel">
                  <i class="glyphicon glyphicon-ban-circle"></i>
                  <span>Cancel</span>
              </button>
          {% } %}
        </td>
    </tr>
{% } %}
</script>

<script type="text/javascript" charset="utf-8">
  function showLoading(open){
    if(open){
      $("#loading-filter-background").show();
    }
    else{
      $("#loading-filter-background").hide();
    }
  }

  $(document).on('ajax:success', '.delete-link', function(){
    $(this).parents('tr').remove();
  });

  $(document).on('ajax:beforeSend', function(){
    showLoading(true);
  });

  $(document).on('click', '.update-link', function(event) {
    event.preventDefault();
    var $that = $(this);
    $.ajax({
      url: $that.data('url'),
      type: 'PUT',
      dataType: 'json',
      data: $that.parents('tr').find('input, textarea, select').serializeArray(),

    })
    .done(function() {
      console.log("success");
    })
    .fail(function() {
      console.log("error");
    })
    .always(function() {
      console.log("complete");
    });

    /* Act on the event */
  });


  $(document).ajaxComplete(function() {
    showLoading(false);
  });

  $(document).ajaxError(function(event, xhr, settings, thrownError) {
    alert('There was an error for one of the uploads!')
  });

  $(document).on('click', '#update-all-link', function(event) {
    event.preventDefault();
    $('.update-link').trigger('click');
    /* Act on the event */
  });
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload({
        dataType: 'json'
      });

      $('#fileupload').bind('fileuploadsubmit', function (e, data) {
        var inputs = data.context.find(':input');
        if (inputs.filter(function () {
                return !this.value && $(this).prop('required');
            }).first().focus().length) {
            data.context.find('button').prop('disabled', false);
            return false;
        }
        data.formData = inputs.serializeArray();
      });
      //
      //Load existing files:
      $.getJSON(document.location.href, function (files) {
        var fu = $('#fileupload').data('blueimp-fileupload'),
          template;
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>

<style type="text/css">
#loading-filter-background {
  display: none;
  position: fixed;
  left: 50%;
  top: 50%;
  margin-left: -100px;
  margin-top: -100px;
  z-index: 10000;
  background: #000;
  opacity: .75;
  filter: alpha(opacity=75);
  height: 200px;
  width: 200px;
  -moz-border-radius: 10px;
  -webkit-border-radius: 10px;
  border-radius: 10px;
}

#loading-filter-image {
  position: relative;
  z-index: 10;
  margin: 0 auto;
  text-align: center;
  top: 60px;
}

.loading-text {
  position: relative;
  top: 80px;
  width: 100%;
  margin: 0 auto;
  text-align: center;
  font-size: 20px;
  color: #fff;
}
a.btn{
  color: white !important;
  text-decoration: none;
}
</style>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


<div id='loading-filter-background' style="display:none">
  <div id='loading-filter-image'>
    <img alt="Spinner" src="http://d2sx8fj3ha7ai7.cloudfront.net/assets/spinner.gif">
  </div>
  <div class='loading-text'>Loading...</div>
</div>